# Generated by Django 4.1.2 on 2022-10-06 02:11

from django.db import migrations,models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='Persona',
            old_name='apellido',
            new_number="edad",
            new_date="fecha_registro",
            new_name="email",
        )
    ]
